### ISSUE TITLE
Design and build a basic indexing resource of IIIF manifests

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#22]
Investigation here to improve or provide seams to add enhancements of things like:
 - TEI
 - non-included AnnotationLists

  - [x] #32 Create a VaticanIIIFResource for indexing Vatican IIIF content
  - [x] #33 Link and enhance record w/ TEI from web url for VaticanIIIFResources
  - [x] #34 Install annotot and import vatican data sample
  - [x] #35 add linked annotationsLists as additional indexed content
