### ISSUE TITLE
Rearrange a few things on the manuscript show page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#329]
Several requirements for moving things around on the manuscript show page have come in at different times, so there are individual tickets for each of them. But they all involve the manuscript show page and likely can be done efficiently at the same time, so I'm creating this ticket just to group them together.

- [x] Ensure that date fields only display in main manuscript metadata section [#309]
- [x] Move Curated Narrative section to just before Parts section [#303]
- [x] Move bibliography field to end of Description section [#318]
- [x] Move item tags to display in Manuscript section [#288]
