### ISSUE TITLE
Facet indexing updates

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#330]
This is a story ticket intended to group several updates requested by BAV having to do with how values are displayed in the facets. 

- [ ] Update indexing of Name facet value with the "[person]" role [#328]
- [ ] Update indexing of Places facet [#327]
- [ ] "Latin" incorrectly indexed as Language facet value?  [#323]
