### ISSUE TITLE
Updates to how we index and/or format TEI elements

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#331]
Grouping several tickets related to how we index and/or format TEI elements.

- [x] Remove comma from serial list of date and name values [#310]
- [x] Remove date downcasing [#308]
- [x] Update how titles are added to Parts section headings [#325]
- [x] Apply name display formatting to manuscript parts metadata values [#287]
