### ISSUE TITLE
As a Vatican Curator, I want to be able to use a widget to set up a comparison between two to four IIIF objects

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#6]
Related to @ggeisler design work in https://github.com/sul-dlss/exhibits/issues/1002

- [ ] #68 setup as a gem later on
- [x] #85 Validate IIIF manifests
- [x] #86 Constrain items added for Mirador widget to 4 
- [x] #87 Style/Add behavior for manifests added via mirador widget UI as panels
- [x] #88 Add "Preview and configure viewer" button/popup to mirador widget
- [x] #91 Add exhibit item autocomplete to to Mirador widget
- [x] #92 Add ability to generate Mirador config/state based on items added to widget
- [x] #93 ⚠️👀Figure out how to pass over mirador state to embeded mirador viewer
- [ ] #105 Add a loading indicator for mirador items
- [x] #106 Allow mirador items in sir-trevor widget to be re-ordered w/ drag and drop
- [x] #176 Exhibit item should be default selection in Mirador widget 
- [ ] #177 Add Instructions and annotation display to modal
- [x] #178 Remove the top-left "x" and window controls from Mirador windows (configuration)
- [x] #179 Only show preview and configure if items are present / mirador widget
- [x] #180 Item Panels, Mirador widget need leftpad/whitespace fix
- [x] #175 Input should be wider for mirador widget manifest input

**Comment by mejackreed** [comment]
AKA Mirador Sir Trevor Widget MSTW

**Comment by mejackreed** [comment]
Closing as no remaining items are a "blocker"
